[package]
name = "hop"
version = "0.1.0"
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
edition = "2018"

[dependencies]
async-std = "^1.5.0"
async-trait = "^0.1.30"
hop-lib = { path = "../lib" }

[dev-dependencies]
async-std = { default-features = true, features = ["attributes"], version = "^1.5.0" }
