[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
edition = "2018"
name = "hop-bin"
version = "0.1.0"

[dependencies]
env_logger = { default-features = false, version = "^0.7.0" }
futures-util = { default-features = false, version = "^0.3.4" }
log = { default-features = false, version = "^0.4.8" }
hop = { package = "hop-lib", path = "../lib" }
smol = { default-features = false, version = "^0.1.2" }
