[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
edition = "2018"
name = "imms-bin"
version = "0.1.0"

[dependencies]
async-std = { default-features = true, version = "^1.5.0" }
env_logger = { default-features = false, version = "^0.7.0" }
futures = { default-features = false, version = "^0.3.4" }
log = { default-features = false, version = "^0.4.8" }
imms = { path = "../lib" }
