[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
categories = ["command-line-utilities"]
description = "Application to run a server instance of the Hop database."
edition = "2018"
homepage = "https://github.com/hopdb/hop"
keywords = ["cache", "database", "db", "hop", "hopdb"]
license = "ISC"
name = "hop-bin"
readme = "README.md"
repository = "https://github.com/hopdb/hop.git"
version = "0.1.0"

[dependencies]
async-std = { default-features = true, version = "^1.5.0" }
env_logger = { default-features = false, version = "^0.7.0" }
log = { default-features = false, version = "^0.4.8" }
hop = { package = "hop-lib", path = "../lib" }
