[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
categories = ["database"]
description = "CLI to communicate with Hop database instances or test commands and procedures."
edition = "2018"
homepage = "https://github.com/hopdb/hop"
keywords = ["cache", "database", "db", "hop", "hopdb"]
license = "ISC"
name = "hop-cli"
readme = "README.md"
repository = "https://github.com/hopdb/hop.git"
version = "0.1.0"

[dependencies]
hop = { default-features = false, path = "../../client" }
hop-cli-lib = { default-features = false, path = "../lib" }
tokio = { default-features = false, features = ["io-std", "io-util", "macros"], version = "^0.2.20" }
