[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
edition = "2018"
name = "hop-cli"
version = "0.1.0"

[dependencies]
hop = { path = "../client" }
hop-lib = { path = "../lib" }
smol = { default-features = false, version = "^0.1.2" }
